name: posix

on:
  push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # workflow_dispatch: null
  # schedule:
  #   - cron: '0 0 * * 0'

env:
  OPENBLAS_COMMIT: "v0.3.30"
  MACOSX_DEPLOYMENT_TARGET: 10.9

jobs:
  build:
    runs-on: [self-hosted, Linux, RISCV64]
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          # - { os: ubuntu-latest, PLAT: i686, INTERFACE64: '0', MB_ML_VER: '2014', MB_ML_LIBC: manylinux}

          # - { os: ubuntu-latest, PLAT: x86_64, INTERFACE64: '0', MB_ML_VER: '2014', MB_ML_LIBC: manylinux}
          # - { os: ubuntu-latest, PLAT: x86_64, INTERFACE64: '1', MB_ML_VER: '2014', MB_ML_LIBC: manylinux}

         #  - { os: ubuntu-latest, PLAT: riscv64, INTERFACE64: '0', MB_ML_VER: '_2_39', MB_ML_LIBC: manylinux}
          - { os: ubuntu-latest, PLAT: riscv64, INTERFACE64: '1', MB_ML_VER: '_2_39', MB_ML_LIBC: manylinux}

        # - { os: macos-14, PLAT: x86_64, INTERFACE64: '0', MB_ML_LIBC: macosx}
        # - { os: macos-14, PLAT: x86_64, INTERFACE64: '1', MB_ML_LIBC: macosx}

          # - { os: macos-latest, PLAT: x86_64, INTERFACE64: '0', MB_ML_LIBC: macosx}
          # - { os: macos-latest, PLAT: x86_64, INTERFACE64: '1', MB_ML_LIBC: macosx}

          # - { os: macos-latest, PLAT: arm64, INTERFACE64: '0', MB_ML_LIBC: macosx}
          # - { os: macos-latest, PLAT: arm64, INTERFACE64: '1', MB_ML_LIBC: macosx}

          # - { os: ubuntu-latest, PLAT: x86_64, INTERFACE64: '0', MB_ML_VER: '_1_2', MB_ML_LIBC: musllinux}
          # - { os: ubuntu-latest, PLAT: x86_64, INTERFACE64: '1', MB_ML_VER: '_1_2', MB_ML_LIBC: musllinux}

          # - { os: ubuntu-24.04-arm, PLAT: aarch64, INTERFACE64: '0', MB_ML_VER: '2014', MB_ML_LIBC: manylinux}
          # - { os: ubuntu-24.04-arm, PLAT: aarch64, INTERFACE64: '1', MB_ML_VER: '2014', MB_ML_LIBC: manylinux}

          # - { os: ubuntu-24.04-arm, PLAT: aarch64, INTERFACE64: '0', MB_ML_VER: '_1_2', MB_ML_LIBC: musllinux}
          # - { os: ubuntu-24.04-arm, PLAT: aarch64, INTERFACE64: '1', MB_ML_VER: '_1_2', MB_ML_LIBC: musllinux}

    env:
      NIGHTLY: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      MB_ML_LIBC: ${{ matrix.MB_ML_LIBC }}
      MB_ML_VER: ${{ matrix.MB_ML_VER }}
      INTERFACE64: ${{ matrix.INTERFACE64 }}
      BUILD_DIR: ${{ github.workspace }}
      PLAT: ${{ matrix.PLAT }}
      OS-NAME: ${{ matrix.os }}

    steps:
    - name: Check user
      run: |
        whoami
        id 
    - name: Install prerequisites
      run: |
        #!/bin/bash
        set -exu

        sudo apt update && sudo apt install make podman docker.io libatomic1 build-essential -y
        
        # # Start Docker daemon if not running
        # sudo usermod -aG docker $(whoami)
        
        # sudo dockerd --host=unix:///var/run/docker.sock --storage-driver=vfs --detach &

        
        docker info
        docker --version

        sudo rm -rf "$HOME/_work/openblas-libs/openblas-libs/dist"
        mkdir -p "$HOME/_work/openblas-libs/openblas-libs"

    - uses: actions/checkout@v4.1.1
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: maxim-lobanov/setup-xcode@v1.6.0
      if: ${{ matrix.os == 'macos-latest' }}
      with:
        xcode-version: '16.0'

    - uses: maxim-lobanov/setup-xcode@v1.6.0
      if: ${{ matrix.os == 'macos-14' }}
      with:
        xcode-version: '15.4'

    - name: Print some Environment variable
      run: |
        echo "PLAT: ${PLAT}"

    # - name: Setup tmate session
    #   if: ${{ failure() }}
    #   uses: mxschmitt/action-tmate@v3
    #   with:
    #     limit-access-to-actor: true

    # - name: Set up QEMU
    #  uses: docker/setup-qemu-action@v3
    - name: Check Environment
      run: |
        nproc --all
        uname -a
        lscpu
        free -h
        df -h
    - name: Build and Test wheels
      env:
        CIBW_ARCHS: ${{matrix.PLAT}}
        CIBW_BUILD_VERBOSITY: 1
        CIBW_BUILD:  "cp39-${{ matrix.MB_ML_LIBC }}_${{matrix.PLAT}}"
        CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.MB_ML_LIBC }}${{matrix.MB_ML_VER}}
        CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.MB_ML_LIBC }}${{matrix.MB_ML_VER}}
        CIBW_MUSLLINUX_X86_64_IMAGE: ${{ matrix.MB_ML_LIBC }}${{matrix.MB_ML_VER}}
        CIBW_MANYLINUX_AARCH64_IMAGE: ${{ matrix.MB_ML_LIBC }}${{matrix.MB_ML_VER}}
        CIBW_MUSLLINUX_AARCH64_IMAGE: ${{ matrix.MB_ML_LIBC }}${{matrix.MB_ML_VER}}
        CIBW_MANYLINUX_RISCV64_IMAGE: ${{ matrix.MB_ML_LIBC }}${{matrix.MB_ML_VER}}
        CIBW_CONTAINER_ENGINE: podman
      run: |
        #!/bin/bash
        set -exu
        cd OpenBLAS
        sudo chown -R $(id -u):$(id -g) . || true
        
        make clean
        
        # Create tarball and pipe directly into docker container
        tar czf - . | docker run \
          --rm \
          --cpus="0" \
          --cpuset-cpus="0-$(($(nproc --all) - 1))" \
          -i \
          quay.io/pypa/manylinux_2_39_riscv64:latest \
          bash -c 'mkdir -p /root/openblas && cd /root/openblas && tar xzf - && export CFLAGS="-fvisibility=protected -Wno-uninitialized" && make -j$(nproc) BUFFERSIZE=20 DYNAMIC_ARCH=1 QUIET_MAKE=1 USE_OPENMP=0 NUM_THREADS=64 BINARY= INTERFACE64=1 SYMBOLSUFFIX=64_ LIBNAMESUFFIX=64_ OBJCONV=/project/objconv/objconv SYMBOLPREFIX=scipy_ LIBNAMEPREFIX=scipy_ FIXED_LIBNAME=1 TARGET=GENERIC'
      
      
    - name: Upload wheels to artifacts
      uses: actions/upload-artifact@v4.3.0
      with:
        name: wheels-${{ matrix.os }}-${{ matrix.PLAT }}-${{ matrix.INTERFACE64 }}-${{ matrix.MB_ML_LIBC }}-${{ matrix.   MB_ML_VER }}
        path: dist/scipy_openblas*.whl
          
          
    - name: Upload openblas to artifacts
      uses: actions/upload-artifact@v4.3.0
      with:
        name: openblas-${{ matrix.os }}-${{ matrix.PLAT }}-${{ matrix.INTERFACE64 }}-${{ matrix.MB_ML_LIBC }}-${{ matrix.   MB_ML_VER }}
        path: dist/openblas*.tar.gz
